Repository codehaus-plexus/plexus-archiver, pull requests merged in 2023-05, with the labels that each got.

#268 Deprecate the JAR Index feature (JDK-8302819)
  src/main/java/org/codehaus/plexus/archiver/jar/JarArchiver.java
Labels: enhancement

#269 Use JUnit TempDir to manage temporary files in tests
  src/test/java/org/codehaus/plexus/archiver/jar/JarArchiverTest.java
  src/test/java/org/codehaus/plexus/archiver/tar/TarArchiverTest.java
  src/test/java/org/codehaus/plexus/archiver/tar/TarFileAttributesTest.java
  src/test/java/org/codehaus/plexus/archiver/util/ArchiveEntryUtilsTest.java
  src/test/java/org/codehaus/plexus/archiver/zip/ZipArchiverTest.java
Labels: maintenance

#270 Use NIO Files for creating temporary files
  src/main/java/org/codehaus/plexus/archiver/zip/DeferredScatterOutputStream.java
  src/main/java/org/codehaus/plexus/archiver/zip/OffloadingOutputStream.java
  src/test/java/org/codehaus/plexus/archiver/BasePlexusArchiverTest.java
  src/test/java/org/codehaus/plexus/archiver/zip/OffloadingOutputStreamTest.java
Labels: enhancement

#279 Override project.url
  pom.xml
Labels: maintenance

#281 Cleanup after "veryLargeJar" test
  src/test/java/org/codehaus/plexus/archiver/jar/JarArchiverTest.java
Labels: java, maintenance

#282 Remove parent and reports menu from site
  src/site/site.xml
Labels: maintenance
